name: PhoneBook deployement

on:
  push:
    branches:
      - main
  

jobs:
    simple_deployment_pipeline:
      runs-on: windows
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Directory change
          run: cd backend
        - name: Directory content
          run: dir
        - name: Install backend dependencies
          run: npm install
        
