name: Health Check

on:
    push:
        branches: [master]
    schedule:
        - cron: '8 12 * * *'      

jobs:
    check_the_server:
      runs-on: ubuntu-20.04
      steps:        
        - name: Check if backend is alive
          uses: jtalk/url-health-check-action@v3
          with:            
            url: https://moryary-phonebook.fly.dev/
            max-attempts: 3 
            retry-delay: 5s
        - name: Server Error
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
                severity: error
                username: Moryarty
                color: '#ff00aa'
                avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
                description: ${{ github.event.description }}
                details: The server is down :(                
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}