name: Hello!

on:
  push:
    branches:
      - main
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory content
        run: ls -l
      - name: Say hello
        run: |
          echo "Hello World!"